// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = "jet";    // Network SSID (name)
const char PASS[]     = "0959202399";    // Network password (use for WPA, or use as key for WEP)

void onMessageChange();

String message;
float ironWeight;
float plasticWeight;
int bottleNum;

void initProperties(){

  ArduinoCloud.addProperty(message, READWRITE, ON_CHANGE, onMessageChange);
  ArduinoCloud.addProperty(ironWeight, READ, 10 * SECONDS, NULL);
  ArduinoCloud.addProperty(plasticWeight, READ, 10 * SECONDS, NULL);
  ArduinoCloud.addProperty(bottleNum, READ, 10 * SECONDS, NULL);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
